package treenirekisteri.test;
// Generated by ComTest BEGIN
import java.io.*;
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
import treenirekisteri.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.04.26 18:25:28 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class MovementsTest {



  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta137 
   * @throws SailoException when error
   */
  @Test
  public void testLueTiedostosta137() throws SailoException {    // Movements: 137
    Movements movements = new Movements(); 
    Movement run = new Movement(); run.rekisteroi(); run.taytaMov(); 
    Movement row = new Movement(); row.rekisteroi(); row.taytaMov(); 
    String kansio = "testitreeni"; 
    String tiedNimi = kansio+ "/movements.dat"; 
    File ftied = new File(tiedNimi); 
    ftied.delete(); 
    try {
    movements.lueTiedostosta(kansio); 
    fail("Movements: 148 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
    movements.lisaa(run); 
    movements.lisaa(row); 
    movements.tallenna(kansio); 
    movements = new Movements();  //poistetaan vanhat luomalla uusi
    movements.lueTiedostosta(kansio);  //johon ladataan tiedot tiedostosta
    Iterator<Movement> i = movements.iterator(); 
    assertEquals("From: Movements line: 156", run.toString(), i.next().toString()); 
    assertEquals("From: Movements line: 157", row.toString(), i.next().toString()); 
    assertEquals("From: Movements line: 158", false, i.hasNext()); 
    movements.lisaa(run); 
    movements.tallenna(kansio); 
    assertEquals("From: Movements line: 162", true, ftied.delete()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testLisaa191 */
  @Test
  public void testLisaa191() {    // Movements: 191
    Movements movements = new Movements(); 
    Movement run = new Movement(); 
    Movement squat = new Movement(); 
    Movement pullUp = new Movement(); 
    assertEquals("From: Movements line: 196", 0, movements.getLkm()); 
    movements.lisaa(run); assertEquals("From: Movements line: 197", 1, movements.getLkm()); 
    movements.lisaa(squat); assertEquals("From: Movements line: 198", 2, movements.getLkm()); 
    movements.lisaa(pullUp); assertEquals("From: Movements line: 199", 3, movements.getLkm()); 
    movements.lisaa(pullUp); assertEquals("From: Movements line: 200", 4, movements.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testHaeLiike272 */
  @Test
  public void testHaeLiike272() {    // Movements: 272
    Movements movements = new Movements(); 
    Movement run = new Movement(), squat = new Movement(), pullUp = new Movement(); 
    run.rekisteroi(); squat.rekisteroi(); pullUp.rekisteroi(); 
    run.taytaMov(); squat.taytaMov(); pullUp.taytaMov(); 
    movements.lisaa(run); movements.lisaa(squat); movements.lisaa(pullUp); 
    Movement uusi = new Movement(); 
    uusi.rekisteroi(); uusi.taytaMov(); 
    uusi = movements.haeLiike(run.gettunnusNro()); 
    movements.lisaa(uusi); 
    assertEquals("From: Movements line: 285", "run", run.getmovNimi()); 
    assertEquals("From: Movements line: 286", "run", uusi.getmovNimi()); 
  } // Generated by ComTest END
}