package treenirekisteri.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import treenirekisteri.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.04.26 18:16:58 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class MovementTest {


  // Generated by ComTest BEGIN
  /** testRekisteroi98 */
  @Test
  public void testRekisteroi98() {    // Movement: 98
    Movement run = new Movement(); 
    assertEquals("From: Movement line: 100", 0, run.gettunnusNro()); 
    run.rekisteroi(); 
    Movement pullUp = new Movement(); 
    pullUp.rekisteroi(); 
    int n1 = run.gettunnusNro(); 
    int n2 = pullUp.gettunnusNro(); 
    assertEquals("From: Movement line: 106", n1+1, n2); 
  } // Generated by ComTest END
}