package treenirekisteri.test;
// Generated by ComTest BEGIN
import java.io.*;
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
import treenirekisteri.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.04.26 18:14:48 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class ResultsTest {



  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta132 
   * @throws SailoException when error
   */
  @Test
  public void testLueTiedostosta132() throws SailoException {    // Results: 132
    Results results = new Results(); 
    Result reeni = new Result(); 
    Result reeni1 = new Result(); 
    reeni.rekisteroi(); 
    reeni1.rekisteroi(); 
    reeni.paivays("1.3.2020"); 
    reeni1.paivays("11.3.2020"); 
    String kansio = "testitreeni"; 
    String tiedNimi = kansio+ "/results.dat"; 
    File ftied = new File(tiedNimi); 
    ftied.delete(); 
    try {
    results.lueTiedostosta(kansio); 
    fail("Results: 150 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
    results.lisaa(reeni); 
    results.lisaa(reeni1); 
    results.tallenna(kansio); 
    results = new Results();  //poistetaan vanhat luomalla uusi
    results.lueTiedostosta(kansio);  //johon ladataan tiedot tiedostosta
    Iterator<Result> i = results.iterator(); 
    assertEquals("From: Results line: 158", reeni.toString(), i.next().toString()); 
    assertEquals("From: Results line: 159", reeni1.toString(), i.next().toString()); 
    assertEquals("From: Results line: 160", false, i.hasNext()); 
    results.lisaa(reeni); 
    results.tallenna(kansio); 
    assertEquals("From: Results line: 164", true, ftied.delete()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testEtsi193 
   * @throws SailoException when error
   */
  @Test
  public void testEtsi193() throws SailoException {    // Results: 193
    Results results = new Results(); 
    Result reeni = new Result(); reeni.parse("1| 1000| 2020-04-16|4"); 
    Result reeni2 = new Result(); reeni2.parse("2| 50000| 2020-04-17|7"); 
    Result reeni3 = new Result(); reeni3.parse("3| 45| 2020-04-20|4"); 
    results.lisaa(reeni); results.lisaa(reeni2); results.lisaa(reeni3); 
    List<Result> loytyneet; 
    loytyneet = (List<Result>)results.etsi(7); 
    assertEquals("From: Results line: 205", true, loytyneet.get(0) == reeni2); 
    assertEquals("From: Results line: 206", 1, loytyneet.size()); 
    loytyneet = (List<Result>)results.etsi(4); 
    assertEquals("From: Results line: 209", true, loytyneet.get(0) == reeni); 
    assertEquals("From: Results line: 210", true, loytyneet.get(1) == reeni3); 
    assertEquals("From: Results line: 211", 2, loytyneet.size()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testEtsiId308 
   * @throws SailoException when error
   */
  @Test
  public void testEtsiId308() throws SailoException {    // Results: 308
    Results results = new Results(); 
    Result reeni = new Result(); reeni.rekisteroi(); 
    Result reeni1 = new Result(); reeni1.rekisteroi(); 
    reeni.paivays("1.3.2020"); 
    reeni1.paivays("11.3.2020"); 
    int id1 = reeni.getRestultId(); 
    results.lisaa(reeni); results.lisaa(reeni1); 
    assertEquals("From: Results line: 319", 1, results.etsiId(id1+1)); 
    assertEquals("From: Results line: 320", 0, results.etsiId(id1)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnnaId335 */
  @Test
  public void testAnnaId335() {    // Results: 335
    Results results = new Results(); 
    Result reeni = new Result(); reeni.rekisteroi(); 
    Result reeni1 = new Result(); reeni1.rekisteroi(); 
    reeni.paivays("1.3.2020"); 
    reeni1.paivays("11.3.2020"); 
    int id1 = reeni.getRestultId(); 
    results.lisaa(reeni); results.lisaa(reeni1); 
    assertEquals("From: Results line: 344", true, results.annaId(id1  ) == reeni); 
    assertEquals("From: Results line: 345", true, results.annaId(id1+1) == reeni1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testLisaa359 */
  @Test
  public void testLisaa359() {    // Results: 359
    Results results = new Results(); 
    Result reeni = new Result(); 
    Result reeni2 = new Result(); 
    Result reeni3 = new Result(); 
    assertEquals("From: Results line: 364", 0, results.getLkm()); 
    results.lisaa(reeni); assertEquals("From: Results line: 365", 1, results.getLkm()); 
    results.lisaa(reeni2); assertEquals("From: Results line: 366", 2, results.getLkm()); 
    results.lisaa(reeni3); assertEquals("From: Results line: 367", 3, results.getLkm()); 
    results.lisaa(reeni); assertEquals("From: Results line: 368", 4, results.getLkm()); 
  } // Generated by ComTest END
}