package treenirekisteri.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import treenirekisteri.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.04.26 18:16:38 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class ResultTest {


  // Generated by ComTest BEGIN
  /** testRekisteroi116 */
  @Test
  public void testRekisteroi116() {    // Result: 116
    Result reeni = new Result(); 
    assertEquals("From: Result line: 118", 0, reeni.getRestultId()); 
    reeni.rekisteroi(); 
    Result reeni2 = new Result(); 
    reeni2.rekisteroi(); 
    int n1 = reeni.getRestultId(); 
    int n2 = reeni2.getRestultId(); 
    assertEquals("From: Result line: 124", n1+1, n2); 
  } // Generated by ComTest END
}