package treenirekisteri.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import treenirekisteri.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.04.26 18:26:02 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class TypeTest {


  // Generated by ComTest BEGIN
  /** testRekisteroi55 */
  @Test
  public void testRekisteroi55() {    // Type: 55
    Type kg = new Type("kg"); 
    assertEquals("From: Type line: 57", 0, kg.getId()); 
    kg.rekisteroi(); 
    Type reps = new Type("reps"); 
    reps.rekisteroi(); 
    int n1 = kg.getId(); 
    int n2 = reps.getId(); 
    assertEquals("From: Type line: 63", n2-1, n1); 
  } // Generated by ComTest END
}